# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- default

pool:
  vmImage: ubuntu-latest
jobs:
  - job: build
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '$(Build.SourcesDirectory)/dotnet-ourchive.sln'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          projects: '$(Build.SourcesDirectory)/ui-tests/*.csproj'
          arguments: '-c Release /p:PublishProfile=$(Build.SourcesDirectory)/ui-tests/Properties/PublishProfiles/FolderProfile.pubxml -o $(Build.ArtifactStagingDirectory)'
          publishWebProjects: false 
          zipAfterPublish: true # boolean. Optional. Use when command = publish. Zip published projects. Default: true.
          modifyOutputPath: true # boolean. Optional. Use when command = publish. Add project's folder name to publish path. Default: true.
        
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          publishLocation: 'pipeline'
          patterns: '**/*.zip'
  - deployment: runUITests # Required as first property. Name of the deployment job, A-Z, a-z, 0-9, and underscore. The word deploy is a keyword and is unsupported as the deployment name.
    displayName: Run UI Tests Against Ourchive-Dev # Human-readable name for the deployment.
    dependsOn: build # Any jobs which must complete before this one.
    #condition: string # Evaluate this condition expression to determine whether to run this deployment.
    #continueOnError: string # Continue running even on failure?
    #timeoutInMinutes: string # Time to wait for this job to complete before the server kills it.
    #cancelTimeoutInMinutes: string # Time to wait for the job to cancel before forcibly terminating it.
    #variables: variables | [ variable ] # Deployment-specific variables.
    pool:
      vmImage: ubuntu-latest
    environment: ourchive-dev # Target environment name and optionally a resource name to record the deployment history; format: environment-name.resource-name.
    #workspace: # Workspace options on the agent.
    #  clean: string # Which parts of the workspace should be scorched before fetching.
    strategy:
      # default deployment strategy, more coming...
      runOnce:
        deploy:
          steps:
          - script: |
              ls 
          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '**/*.zip' # string. Required. Archive file patterns. Default: **/*.zip.
              destinationFolder: '$(agent.builddirectory)' # string. Required. Destination folder. 
